---
# Tasks to install firewalld and fail2ban

- name: Install Ipset, Firewalld, Fail2ban with FirewallD - RHEL
  yum:
    name:
      - ipset
      - firewalld
      - fail2ban-firewalld
      - libselinux-python
    state: latest
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Install Ipset, Firewalld, Fail2ban with FirewallD - Fedora
  dnf:
    name:
      - ipset
      - firewalld
      - fail2ban-firewalld
      - libselinux-python
    state: latest
  when: ansible_distribution == 'Fedora'

- name: Copy fail2ban.local configuration
  template:
    src: fail2ban.local
    dest: /etc/fail2ban/

- name: Copy jail.local configuration for fail2ban
  template:
    src: jail.local
    dest: /etc/fail2ban/
  notify: restart firewalld

- name: Firewalld service state
  service:
    name: firewalld
    state: started
    enabled: yes

- name: fail2ban service state
  service:
    name: fail2ban
    state: started
    enabled: yes

- name: open ports with firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes
  with_items: "{{ open_ports }}"
  tags:
    - open_ports

- name: close ports with firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: disabled
    immediate: yes
  ignore_errors: yes
  with_items: "{{ close_ports }}"
  tags:
    - close_ports
